version: '3.8'

services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow
    ports:
      - "8080:8080"  # Airflow webserver port
    environment:
      - LOAD_EXAMPLES=False
      - EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
    volumes:
      - ./airflow/dags:/opt/airflow/dags  # DAGs directory
      - ./src:/opt/airflow/src            # Scripts directory
    entrypoint: >
      /bin/sh -c "airflow db init &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
      airflow webserver"

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    ports:
      - "8081:8080"  # Jenkins UI port
      - "50000:50000"  # Jenkins agent port
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Jenkins to communicate with Docker
        # Mount Docker CLI
      
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
      - DOCKER_HOST=tcp://host.docker.internal:2375  # Use TCP instead of socket

volumes:
  jenkins_home:
