stages:
  training_pipeline:
    cmd: python src/pipeline/training_pipeline.py
    deps:
      - src/pipeline/training_pipeline.py
      - artifacts/train.csv
      - artifacts/test.csv
    outs:
      - artifacts/preprocessor1.pkl
      - artifacts/random_forest_model.pkl
      - artifacts/metrics.json
 ## Training pipeline has been created and thats why the dvc pipeline is not integrated here . 
 ## To make the dvc pipeline work i need to break my codes into seperate parts.
 ## To run this dvc pipeline dvc.yaml make sure all the file are already there genrated by the training pipeline