stages:
  data_ingestion:
    cmd: python src/components/data_ingestion.py
    deps:
      - src/components/data_ingestion.py
      - train.csv
    outs:
      - artifacts/train.csv
      - artifacts/test.csv

  data_transformation:
    cmd: python src/components/data_transformation.py
    deps:
      - src/components/data_transformation.py
      - artifacts/train.csv
      - artifacts/test.csv
    outs:
      - artifacts/preprocessor1.pkl

  model_training:
    cmd: python src/components/model_trainer.py
    deps:
      - src/components/model_trainer.py
      - artifacts/train.csv
      - artifacts/test.csv
      - artifacts/preprocessor1.pkl
    outs:
      - artifacts/random_forest_model.pkl
      - artifacts/metrics.json

  training_pipeline:
    cmd: python src/pipeline/training_pipeline.py
    deps:
      - src/pipeline/training_pipeline.py
      - artifacts/train.csv
      - artifacts/test.csv
      - artifacts/preprocessor1.pkl
      - artifacts/random_forest_model.pkl
    outs:
      - artifacts/scaler.pkl
      - artifacts/encoder.pkl
      - artifacts/transformed_columns.pkl
      - artifacts/random_forest_model.pkl
      - artifacts/metrics.json
